### PR TITLE
fix unicode apostrophe

### PR DESCRIPTION
**Pull request by binary1230**
this had a unicode apostrophe that I think we were choking on.

error was 
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 984: invalid start byte
```

### CODE REVIEW

**Comment by binary1230** [comment]
merging cause I can't break it more than it already is broken, just changing one line of text.

**Comment by binary1230** [comment]
yup, that fixed it.

**Comment by kitsuta** [comment]
Lol whoops, +1

**Comment by EliAndrewC** [comment]
Ha.  +1

**Pull request merged**
