### PR TITLE
add new background image for labs

### PR DESCRIPTION
**Pull request by migetman9**
Replaces magclassic images with maglabs images. Fixes https://github.com/magfest/magclassic/issues/20.

### CODE REVIEW

**Comment by binary1230** [comment]
question: where's the bg image from and do we need to have an appropriate license for it or whatever?

**Comment by migetman9** [comment]
It is a subtlepattern called ignasi found on http://subtlepatterns.com/ a free-to-use collection of subtle patterns made by random people on the internet.

**Comment by migetman9** [comment]
Oh, guy wants a comment of /* Background pattern from subtlepatterns.com */ somewhere in source code for page its used on

**Comment by kitsuta** [comment]
@migetman9 Can you roll back the change for the tile-background? A PNG won't work and of course we don't want to use this background without credit.

If you want to get rid of the wood texture (which I am totally fine with) you can replace the JPG with a 1x1 blank pixel. That way it won't throw CSS errors but we'll essentially have a solid background until we get the 'proper' background texture.

**Comment by kitsuta** [comment]
I'm apparently wrong about a PNG not working, whoops.

**Comment by binary1230** [comment]
changed this to be "new background image" since I merged the main logo as part of #33

**Comment by EliAndrewC** [comment]
+1 after we add the required attribution

**Comment by binary1230** [comment]
I'm gonna close this one since it was superseded with another PR.  we didn't end up merging that background but could still do that later if we felt like it, probably not a prioirty right now

**Pull request closed without merging**
