### PR TITLE
replace an instances of Classic to Labs

### PR DESCRIPTION
**Pull request by bds002**
Begining the rename of Classic to Labs, we should setup a C.URL to correspond to c.event name

### CODE REVIEW

**Comment by kitsuta** [comment]
The prefest FAQ is changed every year, so while there's nothing wrong with this change, it's also kinda pointless.

**Comment by bds002** [comment]
Yes but it was a new way of testing/deploying things for me through Pycharm. and the new branchless process.

**Comment by kitsuta** [comment]
Gotcha. :)

**Comment by binary1230** [comment]
The changed stuff is all good, your git work looks good.  There's more we can do to un-hardcode this text, but these changes are definitely good progress and a great first start with pycharm. So +1

One note about your commit message, use the imperative mood (command) when making a commit message. I.e. Rather than 'updated language' use 'update language' instead

**Pull request merged**
