### PR TITLE
replace hardcoded date with real date

### LINKED ISSUE #35: Date is incorrect in Attending field
screen shot 2016-06-03 at 10 10 26 am

It should be 9-11, not 11-13.

### PR DESCRIPTION
**Pull request by binary1230**
fixes #35

### CODE REVIEW

**Comment by kitsuta** [comment]
Since this is just the MAGClassic plugin, do we really need the month the second time?

**Comment by kitsuta** [comment]
+1 otherwise

**Comment by binary1230** [comment]
yea we'll fix that later

**Comment by EliAndrewC** [comment]
+1 other than the issue @kitsuta mentioned.

**Pull request merged**
